server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:

        - id: core-service
          uri: http://localhost:7001
          predicates:
            - Path=/gateway/core/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1

        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/gateway/auth/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/