spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstack_db
    username: postgres
    password: 123t456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect